### ISSUE TITLE
Use non-s3 repos

### ISSUE THREAD

**Issue by enboig** [kmwoley/restic-windows-backup#10]
I am interested in your script, but I use a '''rest-server''', I have seen you have marked a TODO to handle non-S3 repos, are you going to implement it?

Thanks.

**Comment by rawtaz** [comment]
I am currently using this with `rest-server`. I don't remember exactly but I believe I simply replaced the repository URL string or something. Either way it was a very minor change.

**Comment by kmwoley** [comment]
Duplicate of #9 - a fix is forthcoming.
