### ISSUE TITLE
FYI backups using VSS failing on 0.17.2

### ISSUE THREAD

**Issue by ilium007** [kmwoley/restic-windows-backup#106]
Maintenance script ran 2 days ago that updated to 0.17.2. There was a push 2 days ago that had VSS changes and these have now broken our backups

https://github.com/restic/restic/pull/5097

https://github.com/restic/restic/issues/5063

```
restic.exe : error: incomplete metadata for D:\: multiple errors occurred: [get named security info failed with: Access is denied.; get EA failed for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy165\, with: get file EA failed with: The parameter is incorrect.]
At C:\restic\backup_us.ps1:288 char:13
+             & $ResticExe backup $ResticBackupFlags $folder_list $vss_ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error: incomple... is incorrect.]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

I have reverted to 0.17.1 and backups running fine again. I have now disabled maintenance until this is resolved.

**Comment by anshibanov** [comment]
i have same behavior

**Comment by yeya** [comment]
It has nothing to do with the PowerShell scripts...
See here: https://github.com/restic/restic/issues/5103

Build the latest by yourself \ wait for the next release \ rollback to previous version

**Comment by ilium007** [comment]
> i have same behavior
> 
> 
> 
> ```
> 
>  2024-10-31 15:44:08 - error: incomplete metadata for D:\: multiple errors occurred: [get named security info failed with: Access is denied.; get EA failed for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy5\, with: get file EA failed with: The parameter
> 
>  is incorrect.] 
> 
> ```
> 
> 
> 
> Could the problem be related to the fact that the target directory (which I am backing up) has a space in the path? @ilium007  Does your target directory have a space?

Revert restic binary to 0.17.1 for now. 0.17.3 will be released in the next few days.

**Comment by innovara** [comment]
`restic` 0.17.3 has been released with a fix

https://github.com/restic/restic/releases/tag/v0.17.3
https://github.com/restic/restic/issues/5107

**Comment by kmwoley** [comment]
restic 0.17.3 fixes this issue; closing
