### ISSUE TITLE
scheduled task in Windows Task Scheduler not working

### ISSUE THREAD

**Issue by flicksolutions** [kmwoley/restic-windows-backup#11]
So if I run ./backup.ps1 from an elevated Powershell myself, everything works fine.
But the Task is not working...

When the task runs, I can see restic.exe run, but it does not consume any CPU load. How can I debug this further?

**Comment by kmwoley** [comment]
What do the log files tell you (if there are any)?
I can tell you that I had to make sure the task was run as an elevated user, and a user with the correct permissions, for Restic to work correctly.

**Comment by flicksolutions** [comment]
I got it to run..!
The Problem is, that I establish the connection with an SSH key. The SYSTEM user has no SSH-Key. That's why it didn't work.
Once I changed the User to someone else with a proper key, it worked!

So maybe you could include that into your readme?

Thank you for this **wonderful piece of software** that helps to get backup right on Windows!
