### ISSUE TITLE
Need to strip rest: in addition to s3: from RESTIC_REPOSITORY

### ISSUE THREAD

**Issue by bhechinger** [kmwoley/restic-windows-backup#14]
I've set this up talking to a Restic REST Server and it fails because you strip the leading `s3:` but not `rest:` so System.Uri doesn't know how to handle the string properly.

Just replace this (Line 219 in the 1.1 release):

```
    $connection_string = $env:RESTIC_REPOSITORY -replace "s3:"
```

To this:

```
    $connection_string = $env:RESTIC_REPOSITORY -replace "s3:|rest:"
```

**Comment by kmwoley** [comment]
@bhechinger - this has been fixed in the most recent release (1.2):
https://github.com/kmwoley/restic-windows-backup/blob/master/CHANGELOG.md
