### ISSUE TITLE
azure repo could not be parsed

### ISSUE THREAD

**Issue by enboig** [kmwoley/restic-windows-backup#15]
My repo is: ```azure:container_name:/repo_folder``` and it complains repo could not be parsed. I checked ```function Invoke-ConnectivityCheck {``` and ```$connection_string``` is "container_name:/repo_folder" but ```$repository_host``` is empty, it should be "azure" or "azure:"

**Comment by kmwoley** [comment]
Check out the latest release and let me know if this doesn't resolve the issue. Thanks for reporting it.
