### ISSUE TITLE
Backup task stucked

### ISSUE THREAD

**Issue by fpopineau** [kmwoley/restic-windows-backup#18]
Hi,
Thanks for putting up  this project. I started to be interested in restic and found your code very up to my needs. After sorting out a few annoyances (ssh-agent emitting a spurious warning and such), I am still puzzled with the scheduled task: when I start it, restic is stucked, 0% cpu, waiting. I have to kill it.
On the other hand, I can run backup.ps1 by hand and it is ok from end to end. 
Any idea ? The only difference I can see is that I run backup.ps1 as Administrator whereas the task scheduler runs the task as NT Authority\System.

Thanks for your insight.

Best regards,

**Comment by fpopineau** [comment]
Answering myself. The problem is linked to the account. The thing to know is that the NT Authority\System account has its .ssh directory located here:
C:\WINDOWS\system32\config\systemprofile\.ssh\
ssh-agent must also be run from the NT Authority\System account.
A valuable helper here is  PsExec from the SysInternal Utils
https://stackoverflow.com/questions/33558772/is-it-possible-to-start-a-process-as-nt-authority-system-over-powershell-remot
Once the connection is setup (sftp in my case) and I can sftp user@server without having to key in anything, then the scripts are ok.

**Comment by kmwoley** [comment]
Thanks for posting your question/issue and the fix. I appreciate it. I struggled to get the right permissions by default for the Task Scheduler invoked job. Maybe NT Authority\System isn't the right account?

**Comment by fpopineau** [comment]
I wondered about the right account too.  I guess that if you are only interested in backuping your own files, then your user account would fit. If you want to backup the whole disk or several accounts, then NT Authority\System is the right one. But it is harder to setup sftp in this case (not mentioning you need a beta version of ssh-agent, because else you get a warning for an unexpected signature format https://github.com/PowerShell/Win32-OpenSSH/issues/1263).

**Comment by kmwoley** [comment]
Agreed. I think I'm going to keep it as NT Authority\System for now since I think that serves the most people. If it becomes an issue, I can update the install script to let the user choose. Thanks for the feedback.
