### ISSUE TITLE
Filtering out errors before deciding to retry ?

### ISSUE THREAD

**Issue by fpopineau** [kmwoley/restic-windows-backup#19]
I started some large backup and I got errors like this :
```
error: open \\?\C:\resticVSS\Source\Exerciser\exerciser\backend\flask\include\python3.6m: The file cannot be accessed by the system.
```
The problem is that these Python virtual envs are using junctions and for some reason, I removed the target of the junction. This is reported as an error by restic. If I am right, the backup script detects the error and decides that it needs a retry. However, no retry will ever succeed with such an error. I wonder what can be done, because it is important to report the restic output, but it should not trigger a retry in this case.

Best regards,

**Comment by rawtaz** [comment]
Isn't there a max number of retries configured? If yes, the worst that will happen is that it will retry a few times.

**Comment by kmwoley** [comment]
Correct; there is a maximum number of retries so it will eventually stop trying. But that's not a great solution to the issue here.

I wonder if the verbosity of Restic can be reduced such that this particular issue doesn't result in an error? 

@fpopineau - you could try to remove the `--verbose` flags that are in `backup.ps1` and see if the error is shown?

**Comment by rawtaz** [comment]
Restic isn't really doing the wrong thing here.. It's asked to back up a file, and it is unable to read that file. The solution to the problem is to not ask it to back up that file, rather than implementing some kind of workaround that hides error messages.

**Comment by fpopineau** [comment]
@kmwoley it seems that even without the verbose flag, errors are reported.
Thinking a bit more about it, I found this issue on restic:
https://github.com/restic/restic/issues/956
which is the right answer I think to the problem. Distinct error codes for different conditions.
At the time being however, the documentation states:
> Note that some issues such as unreadable or deleted files during backup
> currently doesn't result in a non-zero error exit status.
So I am not yet sure of what is happening, because if the exit status is 0 even when  some files are unreadable, I should not observe a retry. Puzzled...

**Comment by fpopineau** [comment]
So I understand what is happening.
As documented, restic returns a 0 exit code when files couldn't be opened.
The backup script in `Invoke-Backup` is testing for the exit code of restic and does not find an error at this stage.
However, later on in `Invoke-Main`, the backup script is using another test to decide if there were an error: it looks at the length of the error file.
So I think that instead of testing the length of the error file, it would be better to test the return codes of both Invoke-Backup and Invoke-Maintenance.
WDYT?

**Comment by kmwoley** [comment]
@fpopineau - thanks for digging into this. 

My philosophy is to be overly aggressive in error checking.

It feels like there's a tradeoff here, and I am biased towards keeping the script as is. Without checking the error log output you never would have known that files you intended to be backed up were not actually being backed up. That's one of the reasons I didn't rely upon only the return value from restic directly. I wanted to know if anything at all had gone amiss. If we go with only looking at the return values, errors like this would be missed. 

Is there a reason excluding the files that restic cannot backup is not an option for you?

**Comment by fpopineau** [comment]
I can understand and definitely respect your strategy regarding errors.

My reason is that I had tens of lines reporting files that could not be accessed and that would have been cumbersome to add them one by one to the exclude file. These were files from Python virtual environments and they used and abused from junctions. Moreover the backup was more than 400Gb, so it took a bit of time.
I'm still discovering restic and your scripts, so I will tinker a bit more before being comfortable.

Thanks for your quick answers.

**Comment by kmwoley** [comment]
@fpopineau thanks! I'm in the same boat re: discovering restic and learning, so I'm open to change. I ran into something similar in my Ubuntu for Windows environment and decided to add those files/directories to my `local.exclude` file, FWIW.

**Comment by eliotmoss** [comment]
I recently opened a new issue related to this.  Some junctions and other kinds of symlinks are perfectly valid from the standpoint of certain programs, notably Cygwin and Windows Subsystem for Linux, but their target cannot be followed by an ordinary Windows program.  These links / junctions need to be backed up as is, without being followed.  Failure to open them is not so much as error to report and a condition that should be treated in a different way.
