### ISSUE TITLE
Dirrectory/Folder Backup

### ISSUE THREAD

**Issue by cloudcafetech** [kmwoley/restic-windows-backup#21]
Sorry I am not good in Powershell, does this backup.ps1 take Dirrectory/Folder Backup.

Looking for separate script for Dirrectory/Folder **`Backup/Restore/Scheduling`** with argument.

**Comment by kmwoley** [comment]
I'm not sure I understand your comment. `backup.ps1` does not take any arguments. Everything is controlled by the configuration .ps1 files. Take a look at those and see if you can find the configuration points you're looking for. Cheers!
