### ISSUE TITLE
SFTP backup

### ISSUE THREAD

**Issue by matri8not** [kmwoley/restic-windows-backup#22]
It seems that secrets.ps1 lack SFTP configuration

**Comment by Phlogi** [comment]
No, you can use just $Env:RESTIC_REPOSITORY='sftp:foo@bar.net:/the/folder/path'.

In case you need to set a port or a specific private key, use the .ssh folder of the user that will run restic. This might be your system user, which has it's ssh settings in "C:\Windows\system32\config\systemprofile\.ssh". Create a config file and rsa_pub key there.
