### ISSUE TITLE
Restic + rclone errors

### ISSUE THREAD

**Issue by Jeff-rgb2** [kmwoley/restic-windows-backup#26]
- I was able to init a repository with your script using restic + rclone
- I'm not able to begin a backup
- Error and log files attached.
- I have copied rclone.exe to the C:\restic directory and still no luck

[20201127T2201243045.err.txt](https://github.com/kmwoley/restic-windows-backup/files/5607538/20201127T2201243045.err.txt)
[20201127T2201243045.log.txt](https://github.com/kmwoley/restic-windows-backup/files/5607539/20201127T2201243045.log.txt)

**Comment by rawtaz** [comment]
The error message clearly tells you what is wrong. The rclone binary cannot be executed because Windows does not find it in any of the directories in your %PATH% environment variable.

You need to put the rclone binary in one of the directories listed in your %PATH% or adjust the %PATH% so that it includes the C:\restic directory.

**Comment by Jeff-rgb2** [comment]
You’ll need to be a bit more specific

- in which file and which row do I configure the %PATH% variable ?

- I’m assuming the %PATH% doesn’t include C:/restic because that is where I’ve copied rclone.exe

**Comment by rawtaz** [comment]
This is completely out of the scope of restic or this wrapper script.

Making your PATH environment variable contain the paths you need for any software you want to run to work, is something that has to do with your Windows configuration.

Here is the very first hit on DuckDuckGo.com when searching for "windows 10 set path": https://www.computerhope.com/issues/ch000549.htm

Please, start researching at least a little bit before asking questions that are super basic. If you do, you will find answers pretty fast ;)

**Comment by Jeff-rgb2** [comment]
Sure and I appreciate your detailed and quick assistance. I googled %path% and %path% restic relevant to me and wasn’t able to find anything. I will revisit my approach using the information above

**Comment by rawtaz** [comment]
The key is that if you don't know what the PATH variable is or is about, you look for information to understand that. When you will be able to solve your initial need.

One shouldn't just try to find a solution to the problem, one should try to understand why the problem happens, and understand what the solution does. Not just copy paste some instructions.

**Comment by kmwoley** [comment]
@Jeff-rgb2 I hope you got your issues sorted out. Let me know if you still need help. Thanks!

**Comment by Jeff-rgb2** [comment]
> @Jeff-rgb2 I hope you got your issues sorted out. Let me know if you still need help. Thanks!

@kmwoley Thank you for reaching out. Firstly thank you for taking the time to create such a fantastic product.

Yes I was able to get my issues sorted. I guess my only other question is what are your thoughts on protecting or encrypting the secrets.ps1 file given it contains the repo password. An adversary would only need that file and they'd have access to my repo. Lmk your thoughts.

**Comment by kmwoley** [comment]
Good question - I’m open to ideas on how to better store the secrets. I
imagine there’s some way to take advantage of some type of key store, but
I’ve never looked into it.

**Comment by rawtaz** [comment]
It's not that uncommon to store your password and similar sensitive information in a file. If this was bad practice in general, restic wouldn't have the `--password-file` and `RESTIC_PASSWORD_FILE` features. There are plenty of examples where secrets are stored in files throughout other operating systems and softwares as well (unencrypted), relying on filesystem permissions and perhaps other similar measures as well.

You just have to make sure that the file in question is only readable by yourself.
