### ISSUE TITLE
backup errors after update to restic 0.12.0 due to --quiet and --verbose being used simultaneously

### ISSUE THREAD

**Issue by shd2h** [kmwoley/restic-windows-backup#29]
Restic 0.12.0 no longer allows the use of --quiet and --verbose at the same time (https://github.com/restic/restic/pull/3205). I'm seeing the backup.ps1 script error out with the below message after updating restic:

```
restic.exe : Fatal: --quiet and --verbose cannot be specified at the same time
At C:\restic\backup.ps1:169 char:9
+         & $ResticExe --verbose -q backup $folder_list --exclude-file= ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Fatal: --quiet ...t the same time:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[[Backup]] Completed with errors
```
```
PS C:\restic> restic version
restic 0.12.0 compiled with go1.15.8 on windows/amd64
```
Stripping out the all the -q (--quiet) flags from backup.ps1 when a --verbose flag is also present in the same command seems to have fixed the issue for me.
I assume rolling back to 0.11.0 would also fix the problem, as my backups ran successfully yesterday before the restic upgrade, but I've not tested this specifically.

Thanks!

**Comment by kmwoley** [comment]
Thanks for reporting this; I'll get it updated in the next release!
