### ISSUE TITLE
Test-Connection: A parameter cannot be found that matches parameter name 'Server'.

### ISSUE THREAD

**Issue by underdpt** [kmwoley/restic-windows-backup#37]
Hello,

First, thanks for these scripts, I found them awesome and of great help.

I'm getting the error on the subject when trying to run `backup.ps1`:

```ps
Test-Connection: A parameter cannot be found that matches parameter name 'Server'.
```

I'm using Powershell 7.1 and when looking at `Test-Connection` parameters i cannot find the `-Server` parameter on versions 5.1 through 7.1 ([here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-7.1)).

Changing line 259 from:

```ps
        elseif(!(Test-Connection -Server $repository_host -Quiet)) {
```

to:

```ps
        elseif(!(Test-Connection -TargetName $repository_host -Quiet)) {

```

does the trick, but i'm also curious as how's possible for this to go unnoticed until now. I'm not a powershell master, so maybe I'm missing something, but maybe there's some conditions that make this piece of code to never be executed?

**Comment by mew1033** [comment]
I'm running powershell 5.1 and `-Server` works, but `-TargetName doesn't. However, I'm having another problem: I'm trying to connect to a server running the restic rest-server (https://github.com/restic/rest-server). The server doesn't respond to ICMP, but the tcp port is open.

**Comment by kmwoley** [comment]
In PowerShell 5.1, `-Server` was an alias for the `-ComputerName` parameter.
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-5.1

Somewhere between 5.1 and 7.1 they removed that alias... and also renamed the `-ComputerName` parameter to `-TargetName`
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-7.1

Thankfully in 7.1 they added the alias `-ComputerName` to `-TargetName`... so, if we all use `-ComputerName` it should work on all versions.
