### ISSUE TITLE
Error on AWS S3 String

### ISSUE THREAD

**Issue by juninhobill** [kmwoley/restic-windows-backup#38]
Hello, just trying those scripts to backup some files to AWS S3 and got this error:

[[Internet]] Repository string could not be parsed.

But the same string were used to create the respository and it worked, but when I tried to run the scheduled task in the windows task scheduler I’m geeting this error. Do you have any ideas on how to make it working??

By the way, the string that I’m using is: "s3:s3.amazonaws.com/xxx.xxx.xxx/BackupTest

Thank you so much!!!

**Comment by kmwoley** [comment]
I updated the URL parsing so that your connection string should work now.
Also, added code to let you disable the internet connectivity check by setting the config value to 0.

Let me know if that doesn't work for you. Thanks for reporting this.

**Comment by juninhobill** [comment]
> I updated the URL parsing so that your connection string should work now.
> Also, added code to let you disable the internet connectivity check by setting the config value to 0.
> 
> Let me know if that doesn't work for you. Thanks for reporting this.

That's great!! I'll test it as soon as I can, thank you so much!!!
