### ISSUE TITLE
Can this be used for bare metal backup and restore?

### ISSUE THREAD

**Issue by maxxer** [kmwoley/restic-windows-backup#43]
Sorry for opening an issue, but I didn't know how else to ask :) I'm more familiar with Linux and I know Restic can do full system backup and restore on [that platform](https://forum.restic.net/t/bare-metal-restore-from-restic-repo-worked-fine/1651).

By reading your instructions it seems your scripts are doing almost the same on Windows, is it that? 

Thanks

**Comment by kmwoley** [comment]
I personally don't think Restic is a good choice for full system backup and
restore on Windows. I don't think any file-based backup system is good for
trying to restore a full Windows machine. I think for that, you're better
off with disk imaging software.

Take a look at the default filters I've put in place in my scripts - they
don't back up a lot of system files. So, if you do try to use these
scripts, you'll want to modify those `.exclude` files.
