### ISSUE TITLE
Can't back up D:\ drive cleanly

### ISSUE THREAD

**Issue by xipmix** [kmwoley/restic-windows-backup#46]
I've tried this and there's something going on with backup of a second drive. I tried with both drives in the config
```
$BackupSources = @{}
$BackupSources["C:\"] = @(
#    'Users'
)
$BackupSources["D:\"] = @(
#
)
```
but backups keep failing with errors  like this:
```
\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\System Volume Information\IndexerVolumeGuid: access is denied
\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\System Volume Information\WPSettings.dat: access is denied
```
These errors repeat each time, with the number after 'HarddiskVolumeShadowCopy' incrementing each time.

I switched to backup of the C: drive in one backup (backupc.ps1, which reads in configc.ps1) and the D: in another (backupd.ps1, reads configd.ps1). The C: drive works fine, the D: drive fails with errors like those shown above.

I did notice this FIXME https://github.com/kmwoley/restic-windows-backup/blob/e826c326b69aefbf30994819cecdd1a133fd48f5/backup.ps1#L133-L138 but commenting out those lines made no difference.

```vssadmin list shadows``` lists no shadows before or after attempting to back up D: alone.

The backups are being done by doing an SSH login to the machine, and running backup to an sftp target. I've checked the account I'm using has admin permissions.

In case it's something to do with the parent snapshot, I also blew away the restic repo and started over (with the two drives in the config), but I get the same error.

**Comment by xipmix** [comment]
A bit of printf debugging... the backup command that backupd.ps1 is running looks like this
```
C:\restic\restic.exe backup D:\ --use-fs-snapshot --exclude-file=C:\restic\windows.exclude --exclude-file=C:\restic\local.exclude
```
windows.exclude is the default one from this repo, local.exclude contains
```
C:\backuppc
C:\cygwin
C:\restic
C:\temp
```
I experimented with excluding ``"C:\System Volume Information"```, to no avail.

Also, I missed one of the error messages. The first error it prints is about being unable to access this uuid-named thing:
```
\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\System Volume Information\6{3808876b-foo3-blah5-gargbacbage}: Access is denied.
```
The uuid inside the ```{}``` is the same for all runs, just the prefixed number changes.

**Comment by rawtaz** [comment]
> \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\System Volume Information\6{3808876b-foo3-blah5-gargbacbage}: Access is denied.

Sounds like your user doesn't have access? Try running this with elevated privileges?

**Comment by kmwoley** [comment]
That sounds like the issue here. Try running a backup command without the
script and see if it works.

**Comment by xipmix** [comment]
I checked the user's group memberships which I thought would confer the right level of access.
```
None Local account and member of Administrators group Administrators Users  NETWORK Authenticated Users
  This Organization Local account CurrentSession NTLM Authentication High Mandatory Level
```
I also did this (the backup runs as user  'backuppc')
```
icacls "C:\System Volume Information" /grant backuppc:F                         
icacls "C:\System Volume Information" /grant backuppc:F /t                      
```

**Comment by kmwoley** [comment]
Interesting idea re: adding `System Volume Information` to the `windows.exclude` - it's currently excluded for the C:\ drive specifically. But maybe adding it as a generic exclude would be a good idea. I'll test it out. Closing this issue for now since you've got your issue resolved.
