### ISSUE TITLE
Error during setup: install.ps1 cannot be loaded because running scripts is disabled on this system

### ISSUE THREAD

**Issue by ianneub** [kmwoley/restic-windows-backup#48]
On my first installation of restic-windows-backup I hit this problem:

```
.\install.ps1 : File C:\restic\install.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
```

Not using Windows too much, I wasn't sure how to enable this. A quick search later and I was able to find a solution pretty easily:
1. https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1
2. https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.1

Run this before `./install.ps1`:
```
Set-ExecutionPolicy Bypass -Scope Process
```

I thought it might help someone else in the future if they run into this issue as well, so posting the solution here.

**Comment by kmwoley** [comment]
Really good feedback! Thanks for sharing it. I added some instructions to the readme.
I would suggest using the RemoteSigned execution policy; it's a little safer / less permissive. 
It does mean you need to 'unblock' the execution of any file that gets downloaded, so it's an bit of an annoyance, but I think it's worth the added security.
