### ISSUE TITLE
Unable to point out to my local repository

### ISSUE THREAD

**Issue by reyzafany** [kmwoley/restic-windows-backup#57]
To be honest I don't know much about programming but I'm interested to backup my app settings before doing a clean install on windows.
So I downloaded latest github restic, created my repo in G:\restic_backup, but I can't for the love of god know how to figure the secrets.ps1
I changed the url to "G:\restic_backup" and it keeps shoving me with this error.
```
Fatal: create repository at <G:\restic_backup> failed: invalid backend
If the repo is in a local directory, you need to add a `local:` prefix
```
Is there any clearer instruction to configure this up? I don't know where to shove this local: prefix
I tried some variation only to end with the same error message like
```
Fatal: create repository at <local:G:\restic_backup> failed: invalid backend
If the repo is in a local directory, you need to add a `local:` prefix
```

**Comment by cdrehner** [comment]
@reyzafany Wondering the same, did you manage to solve this?

**Comment by rawtaz** [comment]
If it's just for reinstalling, just run restic manually.

**Comment by cdrehner** [comment]
Thank you @rawtaz for your reply! I'm trying to setup restic for the first time.
How do I sepcify the target correctly in my secrets.ps1? I have it this way and got the above mentioned error:

> $Env:RESTIC_REPOSITORY='Y:\userbackups\'

**Comment by rawtaz** [comment]
I'm not involved in this project and rarely use PowerShell so I can't give you an answer about the problem really.

I suggest you run restic manually instead, and if you have problems with that you are always free to ask in forum.restic.net if you are stuck on something. The documentation for how to use restic is at restic.readthedocs.io .

**Comment by cdrehner** [comment]
Meanwhile, I figured out it works on a USB drive but not on the SMB share.
Same when I manually run `restic init --repo Y:\userbackups` , 

**-> So this issue can probably be closed**, since it's not an issue of the PowerShell project.

**Comment by kmwoley** [comment]
Thanks for following up - glad you sorted out your issue!
