### ISSUE TITLE
backup not complete , resume after reboot 

### ISSUE THREAD

**Issue by ale82x** [kmwoley/restic-windows-backup#59]
Hello,
thank you for this script :)

i setup today backup my notebook with repo on google drive (by rclone)

but, if i can't terminate backup (because internet at my home is not very fast) i can't shutdown my pc and resume after boot?

in other words , can i upload a little bit every day or i need to upload all my data once in a single job?

thank you
Alex

**Comment by rawtaz** [comment]
Your question is very unclear.

Yes, you can run the script and then terminate restic to stop the backup, and then simply run the script again at a later time to continue backing up, and do so until the first snapshot is finally created due to the backup having completed.

**Comment by ale82x** [comment]
sorry,
my backup (121GB) take more time, 
if i run backup now and shutdown my pc (because i will go out) , of course backup is stopped...

tomorrow when i start my pc and start backup , backup resume (reads data on google drive)
or because snapshot is not complete need to start from  zero?

in other word
data to backup = 121GB
today backup = 10GB 
shutdown pc (backup is not compelte)
tomorrow when i start again backup ,
data to backup is 121GB or 111GB ?

thank you
Alex

**Comment by rawtaz** [comment]
The backup will "resume" so don't worry about it. It will have to scan all the files on the disk again in order to detect what data hasn't already been sent to the repository, but it will only send the data that hasn't already been sent. The answer to your question is 111 GB.

**Comment by ale82x** [comment]
ok thank you 👍 

restic + rclone for is best 🥇 

thanks again
Alex

**Comment by rawtaz** [comment]
Yuo're welcome. Please don't forget to close the issue!
