### ISSUE TITLE
limit upload  bwlimit

### ISSUE THREAD

**Issue by ale82x** [kmwoley/restic-windows-backup#65]
Hello,
for now i have setup a restic backup on my windows devices and works great.

i'm having a trouble because not everywhere i have a large upload bandwidth.

so when restic backup starts , all my internet get very slow.....

reading on restic docs
https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
(my repo is on google drive with rclone)
so seems i can use 
$ export RCLONE_BWLIMIT=1M

but how can i intergrate in script for windows?
 i can edit secrets.ps1 and add
$Env:RCLONE_BWLIMIT=1M

or edit config.ps1 and edit line
$ResticExe = Join-Path $InstallPath $ExeName -o rclone.args="--bwlimit 1M"

thank you in advance

**Comment by kmwoley** [comment]
I would recommend putting that type of config in `config.ps1`, but that's really up to you. I think either should work.
