### ISSUE TITLE
VSS Cleanup Upon Errors

### ISSUE THREAD

**Issue by kmwoley** [kmwoley/restic-windows-backup#8]
If the script is interrupted, it leaves the shadow copy (and directory) in place.
This can lead to a pretty large disk size increase over time.

Simple solution:
`vssadmin.exe delete shadows /all /quiet`

Better:
Keep track of the shadows created by the script, and test/delete by ID
`vssadmin.exe delete shadows /Shadow=<ID> /quiet`

**Comment by rawtaz** [comment]
Thanks for writing a workaround so anyone encountering it will be able to solve it. Will a reboot release shadow copies?

**Comment by kmwoley** [comment]
No, unfortunately shadow copies don’t get released upon reboot.
