### ISSUE TITLE
repository is already locked 

### ISSUE THREAD

**Issue by sickb0y** [kmwoley/restic-windows-backup#90]
Is anyone else encountering problems where the script locks the repository after a successful backup?

I can run the task backup manually without any problems and receive an email confirmation once it's successful. However, following a successful backup, the script continues running and locks the repository. Even if I terminate the task and manually run restic, it still shows the message "repository is already locked." To make the script work the next day, I have to manually unlock the repository via powershell. This is under windows 10, restic 0.16.0, backing to Minio (docker) running on Unraid.

**Comment by jankatins** [comment]
I actually have this now as well: it succeeds because the lock is removed automatically (I installed from git), but I get the email every day.
